package com.nedbank.avo.assessor.domain;

public enum VehicleImageAngle {
	FRONT_PASSENGER_CORNER,
	FRONT_VIEW,
	FRONT_DRIVER_CORNER,
	FRONT_DRIVER_SIDE_DOOR,
	REAR_DRIVER_SIDE_DOOR,
	REAR_DRIVER_CORNER,
	REAR_VIEW,
	REAR_PASSENGER_CORNER,
	REAR_PASSENGER_SIDE_DOOR,
	FRONT_PASSENGER_SIDE_DOOR,
	ODOMETER,
	WINDSCREEN_FROM_INSIDE
}